"""Schemas for User Management CRUD (Admin / System)."""
from pydantic import BaseModel, EmailStr, Field

from app.models.enums import PathLevel, UserRole
from app.schemas.auth import UserOut


class UserCreate(BaseModel):
    email: EmailStr
    name: str = Field(min_length=2, max_length=128)
    password: str = Field(default="Demo@123", min_length=6, max_length=128)
    user_role: UserRole = UserRole.EMPLOYEE
    job_title: str | None = None
    department_code: str | None = None
    job_position_id: str | None = None


class UserUpdate(BaseModel):
    name: str | None = Field(default=None, min_length=2, max_length=128)
    user_role: UserRole | None = None
    job_title: str | None = None
    department_code: str | None = None
    job_position_id: str | None = None
    password: str | None = Field(default=None, min_length=6, max_length=128)


class UserStatusResponse(BaseModel):
    success: bool
    message: str
    user: UserOut


class CvDraft(BaseModel):
    """Profile fields read from a CV (`services/cv_parser.py`); the Admin checks them before creating the account."""
    name: str | None
    email: str | None
    years_of_experience: int | None
    experience_level: PathLevel | None
    previous_experience: str | None
    competencies: list[str]
    # i18n keys of the fields that could not be read, e.g. `cv_warn_no_email`.
    warnings: list[str]


class EmployeeOnboard(BaseModel):
    """Employee account created from a CV. The password is generated by the server and emailed to the employee."""
    email: EmailStr
    name: str = Field(min_length=2, max_length=128)
    job_position_id: str = Field(min_length=1)
    experience_level: PathLevel | None = None
    previous_experience: str | None = Field(default=None, max_length=2000)
    competencies: list[str] = Field(default_factory=list, max_length=20)


class OnboardResult(BaseModel):
    user: UserOut
    email_sent: bool
    # Returned only when the email could not be sent (SMTP not configured or failing), so the Admin can hand it over;
    # when the email is sent the password exists only in the employee's inbox.
    temporary_password: str | None = None
